### ISSUE TITLE
v 0.0.58 todo

### ISSUE THREAD

**Issue by bologer** [bologer/anycomment.io#182]
- [x] translate visual editor
- [x] fix twitter embeds 
- [x] check attachments which are not being delete from table & file system
- [x] add placeholder
- [x] [translate quilll](https://github.com/quilljs/quill/issues/2339#issuecomment-426793283)
